version: '3.8'

services:
  app:
    build: .
    environment:
      - FLUME_CLIENT_ID=${FLUME_CLIENT_ID}
      - FLUME_CLIENT_SECRET=${FLUME_CLIENT_SECRET}
      - FLUME_USERNAME=${FLUME_USERNAME}
      - FLUME_PASSWORD=${FLUME_PASSWORD}
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_MEASUREMENT=${INFLUXDB_MEASUREMENT}
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - influxdb_data:/var/lib/influxdb2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Service for running tests
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - FLUME_CLIENT_ID=${FLUME_CLIENT_ID}
      - FLUME_CLIENT_SECRET=${FLUME_CLIENT_SECRET}
      - FLUME_USERNAME=${FLUME_USERNAME}
      - FLUME_PASSWORD=${FLUME_PASSWORD}
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=test_bucket
      - INFLUXDB_MEASUREMENT=${INFLUXDB_MEASUREMENT}
    depends_on:
      - influxdb

volumes:
  influxdb_data: 